/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin. 
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2024-05-07 17:04:38
 */
package uof0.cosmic.debug;

import kd.cosmic.debug.tools.CosmicLauncher;

/**
 * 启动本地应用程序(微服务节点)
 */
public class DebugApplication {
	
	

    public static void main(String[] args) {
    	
//    	Thread.currentThread().setContextClassLoader(new KDSecurityClassLoader(Thread.currentThread().getContextClassLoader()));
    	
        CosmicLauncher cosmic = new CosmicLauncher(false);

//        cosmic.setMcServerUrl("http://127.0.0.1:8090");
        cosmic.setCosmicWepPort(8080);
//        cosmic.setConfigUrl("127.0.0.1:2182?user=zk&password=xxxxxx");
        cosmic.setFsServerUrl("127.0.0.1", 8100);
        cosmic.setImageServerUrl("127.0.0.1", 8100);

        cosmic.setClusterNumber("cosmic");
        cosmic.setTenantNumber("ierp");
        cosmic.setStartWithQing(true);
        
        cosmic.setConfigUrl("222.20.105.86:2181?user=zookeeper&password=zookeeper");
//        cosmic.setConfigUrl("222.20.105.86:2181");
        
//        cosmic.setMcServerUrl("http://127.0.0.1:8090");
        cosmic.setMcServerUrl("http://222.20.105.86:8090/"); 

//        cosmic.setWebResPath("D:/jindie/SoftWareCup/static-file-service");
        
//        cosmic.setFsServerUrl("127.0.0.1", 8100);
//        cosmic.setImageServerUrl("127.0.0.1", 8100);
        cosmic.setCosmicWepPort(8881);
        cosmic.setMqConsumerRegister(true,"");

//        cosmic.setDubboConfig(false, true, true);
        cosmic.start();
        
        
    }
}